### ISSUE TITLE
ihave a question about if wether i am using crossroads incorrectly

### ISSUE THREAD

**Issue by buttonlover427** [Gaider10/CrossroadFinder#16]
i am trying to find a good fortress on the seed -7015078764918145110
and having trouble the cords that are out puted do not match where nether strongholds are located this is my text log please let me know if i am using it wrong t is vanilla structures

Enter closest lower version:
0 - 1.7
1 - 1.13
2 - 1.16.1
3 - 1.18
3
Using closest lower version 1.18

Enter numeric world seed
-7015078764918145110
Using numeric world seed -7015078764918145110

Enter fortress salt (leave empty for 30084232):
0
Using fortress salt 0

Enter crossroad shape:
0 - DOUBLE
1 - TRIPLE_LINE
2 - QUAD_LINE
3 - QUINT_LINE
4 - TRIPLE_CORNER
5 - QUAD_SQUARE
6 - QUINT_BLOB
6
Using crossroad shape QUINT_BLOB

Enter maxY (leave empty for 255):
48
Using maxY 48

Enter search radius:
90000
Using search radius 90000

Enter search center X (leave empty for 0):
345448
Using search center X 345448

Enter search center Z (leave empty for 0):
176072
Using search center Z 176072

Found a good shape at /tp 263346 48 159471
there were other tp locations but just using the one as an example

**Comment by grillotine** [comment]
i checked the seed and coords you listed and there was no fortress there. i ran a search using the same parameters you did and the first 3 were good so i assume they all are;
Enter closest lower version:
0 - 1.7
1 - 1.13
2 - 1.16.1
3 - 1.18
3
Using closest lower version 1.18

Enter numeric world seed
-7015078764918145110
Using numeric world seed -7015078764918145110

Enter fortress salt (leave empty for 30084232):

Using fortress salt 30084232

Enter crossroad shape:
0 - DOUBLE
1 - TRIPLE_LINE
2 - QUAD_LINE
3 - QUINT_LINE
4 - TRIPLE_CORNER
5 - QUAD_SQUARE
6 - QUINT_BLOB
6
Using crossroad shape QUINT_BLOB

Enter maxY (leave empty for 255):
48
Using maxY 48

Enter search radius:
90000
Using search radius 90000

Enter search center X (leave empty for 0):
345448
Using search center X 345448

Enter search center Z (leave empty for 0):
176072
Using search center Z 176072

Found a good shape at /tp 261666 48 258655
Found a good shape at /tp 267970 48 231727
Found a good shape at /tp 278946 48 154428
Found a good shape at /tp 278690 48 195874
Found a good shape at /tp 295810 48 228652
Found a good shape at /tp 312514 48 145874
Found a good shape at /tp 335474 48 224060
Found a good shape at /tp 368690 48 222914
Found a good shape at /tp 381004 48 243810
Found a good shape at /tp 387084 48 129413
Found a good shape at /tp 395410 48 184514
Found a good shape at /tp 400940 48 217935
Found a good shape at /tp 403759 48 167970
Found a good shape at /tp 413020 48 241778
Press any key to continue . . .
the only thing i can think of would be if the terrain you are searching was generated in a different version than youre using to search. other than than no idea why it wouldnt work. 


edit - i didnt notice you set the fortress salt to 0 and when i repeat the test doing that as well i get the same incorrect results you did, so it looks like that was the issue. no idea what that actually does but i always just left it to default.
