### ISSUE TITLE
Build on Linux

### ISSUE THREAD

**Issue by krishean** [Gaider10/CrossroadFinder#4]
I was able to get this to build on Linux (Xubuntu 18.04) with a few changes to main.c and util\Inputs.c:

main.c: added `#include <limits.h>` under the line for time.h (for INT_MIN and INT_MAX)
main.c: changed `BlockBox *main` to `BlockBox *mainBox` in processRegion and updated any references to it (compiler doesn't like the main function and a variable to have the same name)
main.c: system("pause"); doesn't work on Linux, so I changed it to this:
```
#ifdef _WIN32
    system("pause");
#else
    printf("Press enter to continue . . . ");
    getchar();
    printf("\n");
#endif
```

util\Inputs.c: compiler warns of unused value from fgets so I changed the two `fgets(input, 64, stdin);` lines to this:
```
if (fgets(input, 64, stdin) == NULL) {
    printf("Error was encountered from fgets\n");
    return 0;
}
```

I also checked that it still builds and runs correctly using MingGW64 on windows with these changes applied.

**Comment by f4sak3n** [comment]
Thanks for adding this. For some reason I expected code developed in C to be system agnostic. It's been a while since I looked at any C code so I had forgotten that C != portable C. FWIW, the maintainer should look at incorporating this simple fixes.

**Comment by Gaider10** [comment]
Thanks for noticing, it should build on linux now
