### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by 6Foxy** [Gaider10/CrossroadFinder#8]
can someone explain to me how to use the crossroadfinder?

**Comment by Gaider10** [comment]
Download the exe from releses and run it, then type what it asks

**Comment by JohnHadish** [comment]
**Windows Operating System:** Download and run the `exe` file located in the [release section on the right side](https://github.com/Gaider10/CrossroadFinder/releases/tag/v1.2) of the git repository.
**Linux Operating System** Clone the directory, run the gcc command located in the `complile.txt` from a terminal window. This will compile the file, and create a new file called `main*`. Run this file by typing `./main`, and follow instructions on prompt. 
**Mac Operating System** You will need to install gcc, then run the gcc command from the `compile.txt` file in the same manner as linux
